site_name: 😴 CheatSheet LazyGit
theme:
  name: simple-blog
  language: fr

extra_css:
  - stylesheet  s/extra.css

nav:
  - Accueil: index.md
  - Installation: installation.md
  - Utilisation: usage.md

site_description: Guide d'utilisation de LazyGit
site_author: Sofiane
repo_url: https://github.com/jesseduffield/lazygit
repo_name: jesseduffield/lazygit

plugins:
  - search:
      lang: fr